# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmUnit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmUnit(object):
    def setupUi(self, FrmUnit):
        FrmUnit.setObjectName("FrmUnit")
        FrmUnit.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(FrmUnit)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 20, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.PB_user = QtWidgets.QPushButton(self.centralwidget)
        self.PB_user.setGeometry(QtCore.QRect(370, 120, 93, 28))
        self.PB_user.setObjectName("PB_user")
        FrmUnit.setCentralWidget(self.centralwidget)

        self.retranslateUi(FrmUnit)
        QtCore.QMetaObject.connectSlotsByName(FrmUnit)

    def retranslateUi(self, FrmUnit):
        _translate = QtCore.QCoreApplication.translate
        FrmUnit.setWindowTitle(_translate("FrmUnit", "MainWindow"))
        self.label.setText(_translate("FrmUnit", "UNIT"))
        self.PB_user.setText(_translate("FrmUnit", "User"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrmUnit = QtWidgets.QMainWindow()
    ui = Ui_FrmUnit()
    ui.setupUi(FrmUnit)
    FrmUnit.show()
    sys.exit(app.exec_())
