# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmUser(object):
    def setupUi(self, FrmUser):
        FrmUser.setObjectName("FrmUser")
        FrmUser.resize(252, 242)
        self.centralwidget = QtWidgets.QWidget(FrmUser)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 40, 221, 191))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.idUserLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.idUserLabel.setObjectName("idUserLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.idUserLabel)
        self.Txt_id_user = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Txt_id_user.setObjectName("Txt_id_user")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Txt_id_user)
        self.namaLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.namaLabel.setObjectName("namaLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.namaLabel)
        self.Txt_nama = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Txt_nama.setObjectName("Txt_nama")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Txt_nama)
        self.passwordLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.Txt_password = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Txt_password.setObjectName("Txt_password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Txt_password)
        self.roleLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.roleLabel.setObjectName("roleLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.roleLabel)
        self.Cmb_role = QtWidgets.QComboBox(self.formLayoutWidget)
        self.Cmb_role.setEnabled(True)
        self.Cmb_role.setEditable(True)
        self.Cmb_role.setDuplicatesEnabled(False)
        self.Cmb_role.setObjectName("Cmb_role")
        self.Cmb_role.addItem("")
        self.Cmb_role.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Cmb_role)
        self.PB_add = QtWidgets.QPushButton(self.formLayoutWidget)
        self.PB_add.setObjectName("PB_add")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.PB_add)
        self.PB_update = QtWidgets.QPushButton(self.formLayoutWidget)
        self.PB_update.setObjectName("PB_update")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.PB_update)
        self.PB_exit = QtWidgets.QPushButton(self.formLayoutWidget)
        self.PB_exit.setObjectName("PB_exit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.PB_exit)
        self.PB_del = QtWidgets.QPushButton(self.formLayoutWidget)
        self.PB_del.setObjectName("PB_del")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.PB_del)
        self.PB_pesan = QtWidgets.QPushButton(self.centralwidget)
        self.PB_pesan.setGeometry(QtCore.QRect(80, 260, 93, 28))
        self.PB_pesan.setObjectName("PB_pesan")
        FrmUser.setCentralWidget(self.centralwidget)

        self.retranslateUi(FrmUser)
        QtCore.QMetaObject.connectSlotsByName(FrmUser)

    def retranslateUi(self, FrmUser):
        _translate = QtCore.QCoreApplication.translate
        FrmUser.setWindowTitle(_translate("FrmUser", "Form User"))
        self.label.setText(_translate("FrmUser", "USER"))
        self.idUserLabel.setText(_translate("FrmUser", "Id User"))
        self.namaLabel.setText(_translate("FrmUser", "Nama"))
        self.passwordLabel.setText(_translate("FrmUser", "Password"))
        self.roleLabel.setText(_translate("FrmUser", "Role"))
        self.Cmb_role.setItemText(0, _translate("FrmUser", "Admin"))
        self.Cmb_role.setItemText(1, _translate("FrmUser", "User"))
        self.PB_add.setText(_translate("FrmUser", "Add"))
        self.PB_update.setText(_translate("FrmUser", "Update"))
        self.PB_exit.setText(_translate("FrmUser", "Exit"))
        self.PB_del.setText(_translate("FrmUser", "Delete"))
        self.PB_pesan.setText(_translate("FrmUser", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrmUser = QtWidgets.QMainWindow()
    ui = Ui_FrmUser()
    ui.setupUi(FrmUser)
    FrmUser.show()
    sys.exit(app.exec_())
